services:
    # chanzo_student_performance_db:
    #     image: ankane/pgvector
    #     restart: always
    #     ports:
    #         - "${CHANZO_STUDENT_PERFORMANCE_LONG_TERM_MEMORY_DB_PORT:-6432}:5432"
    #     environment:
    #         - POSTGRES_USER=${CHANZO_STUDENT_PERFORMANCE_LONG_TERM_MEMORY_DB_USER}
    #         - POSTGRES_PASSWORD=${CHANZO_STUDENT_PERFORMANCE_LONG_TERM_MEMORY_DB_PASSWORD}
    #         - POSTGRES_DB=${CHANZO_STUDENT_PERFORMANCE_LONG_TERM_MEMORY_DB_NAME}
    #     volumes:
    #         - chanzo_student_performance_db_data:/var/lib/postgresql/data
    #         - ./container_scripts:/docker-entrypoint-initdb.d
    #     networks:
    #         - chanzo_student_performance_network

    chanzo_app_db:
        image: mysql:8.0.41
        restart: always
        ports:
            - "${CHANZO_APP_DB_PORT:-4306}:3306"
        environment:
            - MYSQL_USER=${CHANZO_APP_DB_USER}
            - MYSQL_PASSWORD=${CHANZO_APP_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${CHANZO_APP_DB_PASSWORD}
            - MYSQL_DATABASE=${CHANZO_APP_DB_NAME}
        volumes:
            - chanzo_app_db_data:/var/lib/mysql
            - ./chanzo_app_db_container_scripts:/docker-entrypoint-initdb.d
        networks:
            - chanzo_student_performance_network

    chanzo_agent_db:
        image: mysql:8.0.41
        restart: always
        ports:
            - "${CHANZO_AGENT_DB_PORT:-4307}:3306"
        environment:
            - MYSQL_USER=${CHANZO_AGENT_DB_USER}
            - MYSQL_PASSWORD=${CHANZO_AGENT_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${CHANZO_AGENT_DB_PASSWORD}
            - MYSQL_DATABASE=${CHANZO_AGENT_DB_NAME}
        volumes:
            - chanzo_agent_db_data:/var/lib/mysql
            - ./chanzo_agent_db_container_scripts:/docker-entrypoint-initdb.d
        networks:
            - chanzo_student_performance_network

volumes:
    # chanzo_student_performance_db_data:
    chanzo_app_db_data:
    chanzo_agent_db_data:

networks:
    chanzo_student_performance_network:
        driver: bridge
